name: Build & Deploy
on:
  push:
  workflow_dispatch:

jobs:
  vite-mikrofrontend:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/vite-mikrofrontend.yaml@mikrofrontend
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      app: dialogmote-mikrofrontend
      id: syfo-dialog
